### ISSUE TITLE
How did you sniff the protocol?

### ISSUE THREAD

**Issue by mark-hahn** [jterrace/pyharmony#7]
I have implemented that config example in the code (using the gatorade fork) and the config query works great.  But I am unable to get the VolumeDown keypress example to work.  I have tried to sniff my wifi with wireshark to see the packets but my laptop's adapter and/or driver can't capture anything but it's own traffic.  How did you two, @jterrace and @petele, capture the packets?  Is there any trick other than the normal airmon-ng and wireshark stuff?

If I can get this to work I _promise_ I'll release a new generation of code with some of the to-do list filled out.

My failed communication is below.  Any idea what could be wrong?  I added the timestamp=0 based on another issue here but it didn't make a difference.  I can tell the command is parsed properly because if I misspell anything I get worse errors.

```
Request:
     <iq type="get" id="#{identity}">
       <oa xmlns="connect.logitech.com"                  
           mime="vnd.logitech.harmony/vnd.logitech.harmony.engine?holdAction">
          action={"command"::"VolumeDown","type"::"IRCommand", "deviceId"::"19685842"}:status=press:timestamp=0
       </oa>
     </iq>
```

```
Response:
    <iq id="278a394f-4d9e-43cf-bc26-5dd204b837bd" to="278a394f-4d9e-43cf-bc26-5dd204b837bd" type="get">
      <oa xmlns='connect.logitech.com' mime='vnd.logitech.harmony/vnd.logitech.harmony.engine?holdAction' 
          errorcode='504' errorstring='Insufficient Arguments'>
      </oa>
    </iq>

```

**Comment by jterrace** [comment]
I used tcpdump on my DD-WRT

**Comment by mark-hahn** [comment]
Wow.  That was a quick response.  Thanks.  A DD-WRT sounds really cool.
I'll check it out.

**Comment by brendandebeasi** [comment]
You can also use something like Charles proxy or Wireshark

**Comment by mark-hahn** [comment]
Wireshark can't sniff wifi on windows and my only unix box is my laptop
which doesn't have the right driver/adapter.  And I just discovered I can't
run DD-WRT on my DIR-655 router.  Maybe I can pick up a cheap router.

I'll keep investigating.  Thanks for the tips.

**Comment by jterrace** [comment]
I had the same issue - I wasn't able to get Wireshark to run on my wifi network. I already had DD-WRT on my router, so I was able to SSH in and run tcmpdump, then open that output file in Wireshark.

**Comment by brendandebeasi** [comment]
Charles runs cross-platform and is pretty easy to setup. The free trial works with only a nag screen.

**Comment by mark-hahn** [comment]
> Charles runs cross-platform and is pretty easy to setup.

**Comment by mark-hahn** [comment]
My understanding is that an adapter/driver will either be able to capture promiscuous wifi traffic or not be able to, no matter what the software.  Mine apparently cannot.  I tried wireshark and tcpdump and tshark.

**Comment by mark-hahn** [comment]
Possibly stupid question.  Does the wifi traffic, particularly the harmony traffic, appear also on the wired lan?  Is it like a bridge or a router?  

Oh, I guess I answered my own question.  It is called a router.  So it _was_ a stupid question.

**Comment by brendandebeasi** [comment]
You would basically want to capture the traffic between your iPhone and the harmony link. If you follow the iPhone setup on the charles website, enabled charles on your computer, and then open / run the harmony app you can sniff the traffic.

**Comment by mark-hahn** [comment]
>  If you follow the iPhone setup on the charles website,

That sounds cool.  Now I have to see if it works on an android.

**Comment by mark-hahn** [comment]
OK, I am stuck again.  Android could only proxy the browser.  So I dug up an old iPad.  I installed Charles on a windows PC, set it up as a proxy, and pointed the iPad proxy at it.  

I could see traffic from the harmony IOS app but it was only the HTTP traffic.  The app would go to port 8088 on the hub, get an HTTP ping, and then start using xmpp.  The xmpp would talk directly to the hub and not use my proxy.  I'm sure this is what was happening because when shutting down the proxy the remote would keep working until the app detected the missing ping and started asking to connect to a hub. 

So I am back to square one.  Any ideas?

**Comment by mark-hahn** [comment]
I'll continue to post my progress here in case someone feels masochistic enough to follow this.

I'm back to square zero.  I found an old linksys wrt54g router in my junk pile and even found a power adapter that worked.  After much effort I'm now running dd-wrt on it.  I've configured it several different ways and it works great.  Cool software.

I was kind of baffled as to why the tiny busybox linux was missing key commands like `ls`, `df`, `ipkg`, etc.  After poking around in settings I discovered that I have a whopping 300 KB of ram remaining of my 8 MB total.  I now realize there is no hope of running anything like tcpdump on it.

so ...
- my commands to the hub are missing some unknown arguments
- I was unable to sniff the wifi network from my unix laptop because of driver/adapter
- Charles didn't work (ignored all traffic) on my linux laptop
- Charles worked on windows laptop but android proxy only worked on browser
- iPad proxied the harmony app but only for http, not xmpp
- I don't want to mess with my verizon fios router (probably couldn't do anything anyway)
- My old wrt54g router runs dd-wrt but it doesn't have enough ram to run tcpdump

I have had unbelievable luck finding stuff to try.  Many things almost worked.  But I'm screwed, at least for now.

**Comment by jterrace** [comment]
I think I followed these instructions to install tcpdump:
http://emtunc.org/blog/04/2011/installing-tcpdump-on-dd-wrt-wrt54gl/

You do have to be careful to write a very explicit filter when capturing, since you don't have much space available.

**Comment by mark-hahn** [comment]
I tried those instructions.  My dd-wrt doesn't have JFFS2 nor the ipkg
command.  I assume this is because of the small amount of ram in my
particular wrt54g.  Despite the same name, there are many versions with
different amounts of ram and flash.  I can replace my linksys code with
dd-wrt as alternative router software but I doubt I could run anything else
at the same time.  I can't even install anything else, no matter how small.

I have one more piece of hardware here.  That is an HP-stream mini
desktop.  It has wifi built-in.  I'll see if I can find a solution using
that.  If not then I'm going to have to get new hardware.  Either a USB
wifi adapter or different router.

**Comment by brendandebeasi** [comment]
If you have a jailbroken iPhone I believe you can use tcpdump locally.

**Comment by mark-hahn** [comment]
> If you have a jailbroken iPhone 

The only ios product I have is an old iPad 2.  It is running ios6 which is not breakable.  I could upgrade to the latest ios8 but I'd get ios8.3 which is also not breakable.

A sane person would give up after all I've gone through but golly-darn-it I'm not giving up.  I'll look into cheap hardware I could buy.

**Comment by brendandebeasi** [comment]
You can almost certainly run tcpdump on android. I just have experience with iOS
http://www.kandroid.org/online-pdk/guide/tcpdump.html http://www.kandroid.org/online-pdk/guide/tcpdump.html

**Comment by mark-hahn** [comment]
> You can almost certainly run tcpdump on android.

I hadn't considered actually running tcpdump on my phone.  I just tried using the charles proxy on windows and enabling a proxy on android.

I'll try it but it looks like a lot of work.  But hey, what's another day after two whole days.  (grin)  It's a good thing I'm retired.

 I'll have to break my phone to get root, put android tools on my pc, and learn all this stuff.  And then it may not work.  I'll google to see if the wifi chip in my galaxy note 3 can go into monitor mode.

**Comment by mark-hahn** [comment]
BTW, the broadcom chip in the HP stream mini doesn't support monitor mode.  So I've tried 8 (!) ways to sniff my wifi.  Running tcpdump on android will be my ninth.

**Comment by mark-hahn** [comment]
I just ordered a Panda USB Adapter.  The web says it works well in monitor mode.  I'll get it tomorrow and let you know how it goes and hopefully give you updated details on xmpp commands.

**Comment by mark-hahn** [comment]
I finally captured the packets with wireshark.  They look pretty much the same as my requests that failed.  The only difference is the `id` field appears to be something keyed to my phone.  It is `88413ad726cb858#hltetmo#sm-n900t-28-19` where `sm-n900t` is the model of my phone.  The security auth key is in the `from` field, not the `id`.  I have copied that `id` field value to my `id` field and I'm still getting the "not enough arguments" error.  i definitely have the same number of arguments.  I'll do more captures to see if that `id` field changes.

A tidbit of info: The `press` and `release` requests are 10 to 100 ms apart.  There is no way my finger is that fast.  So the phone is sending them both when I press (or maybe release) the key on my phone.

**Comment by mark-hahn** [comment]
I give up.  Logitech won the battle.

I've spent the last two days writing my software to send out exactly what the phone sent out and I keep getting that  "not enough arguments" error.  `getConfig` works but `startActivity` and `holdAction` give that error.

I even studied the xmpp rfc to understand the wireShark capture exactly.  I learned what all the miscellaneous fields in the xml packets meant and where necessary I put in my own.  I was optimistic and I continually improved my app until is was a great module to do everything with the hub.  It is great except that it doesn't work.

As much as it pains me I'm going to buy some IR emitter that I can control for sure to sit next to the hub. Does anyone have any suggestions?  I'll do a bunch of googling. 

P.S.  If I was a paranoid person I'd think logitech put some low level key below the xmpp protocol just to block doing what we want.  In other words the missing argument is hidden. Needless to say I'm not going to look at packets at the tcp/ip level.

**Comment by mark-hahn** [comment]
For any lurkers in the future:

I ended up using an iTach flex wifi.  This is a little device the size of a stick of gum.  It learns and sends IR over wifi and has a large database of codes.  It has a well-documented api for developers.  You can use http requests or talk directly over tcp/ip, which is what I did.  I highly recommend it.  The negative is that it costs more then $90, but it was the cheapest wifi solution.
